/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@code-dimension/stencil-components';


declare global {

  namespace StencilComponents {
    interface WarpViewEditorLite {
      'config': any;
      'heightLine': number;
      'heightPx': number;
      'theme': string;
      'warpscript': string;
      'widthPx': number;
    }
  }

  interface HTMLWarpViewEditorLiteElement extends StencilComponents.WarpViewEditorLite, HTMLStencilElement {}

  var HTMLWarpViewEditorLiteElement: {
    prototype: HTMLWarpViewEditorLiteElement;
    new (): HTMLWarpViewEditorLiteElement;
  };
  interface HTMLElementTagNameMap {
    'warp-view-editor-lite': HTMLWarpViewEditorLiteElement;
  }
  interface ElementTagNameMap {
    'warp-view-editor-lite': HTMLWarpViewEditorLiteElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'warp-view-editor-lite': JSXElements.WarpViewEditorLiteAttributes;
    }
  }
  namespace JSXElements {
    export interface WarpViewEditorLiteAttributes extends HTMLAttributes {
      'config'?: any;
      'heightLine'?: number;
      'heightPx'?: number;
      'onWarpViewEditorLoaded'?: (event: CustomEvent) => void;
      'onWarpViewEditorWarpscriptChanged'?: (event: CustomEvent) => void;
      'theme'?: string;
      'warpscript'?: string;
      'widthPx'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
